spring.datasource.url=${MYSQL_PROD_URL}
spring.datasource.username=${MYSQL_PROD_USERNAME}
spring.datasource.password=${MYSQL_PROD_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

logging.level.co.edu.sena.productsreact=INFO
logging.level.org.hibernate.SQL=WARN
